### ISSUE TITLE
Weird loading 

### ISSUE THREAD

**Issue by motschel123** [motschel123/Project_Risiko#12]
Beim Laden von den Daten aus countryLocations.csv werden manchmal einzelne werte falsch/gar nicht geladen.

(Einfach mal mehrere male die main klasse ausführen und auf die zahlen ("0") achten)
(v.a. bei Aschaffenburg, Roth un Schwandorf)

**Comment by SlaynAndKorpil** [comment]
omw

**Comment by SlaynAndKorpil** [comment]
Liegt anscheinend an der Graphic. Wenn das Fenster nicht maximiert ist, sind die Zahlen richtig positioniert.

**Comment by motschel123** [comment]
Man muss das fenster resizen dann sind die anzeigen richtig

**Comment by SlaynAndKorpil** [comment]
Fixed
