### ISSUE TITLE
Coutries and Cards conflict

### ISSUE THREAD

**Issue by motschel123** [motschel123/Project_Risiko#7]
Initiating the countries requires intiated cards. 
BUT initating a card requires a country which in return requires cards to be initated already.

Possible solution: initiating card with only the country name (String) as field (instead of a country instance). 
YELP ME
WE NEED TO WORK TOGETHER AND PROGRAM SO WE FINISH IN TIME!!!!!!11!1!elf!11

**Comment by SlaynAndKorpil** [comment]
omw

**Comment by SlaynAndKorpil** [comment]
Fixed in b7ef902, pls review before merging!
